# Generated by Django 3.2.7 on 2021-09-19 20:59

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_name', models.CharField(max_length=120)),
                ('post_url', models.URLField()),
                ('post_title', models.CharField(max_length=120)),
                ('post_subtitle', models.TextField()),
                ('post_text', models.TextField()),
                ('vector_column', django.contrib.postgres.search.SearchVectorField(null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='post',
            index=django.contrib.postgres.indexes.GinIndex(fields=['vector_column'], name='core_post_vector__7c6813_gin'),
        ),
    ]
