# Generated by Django 3.2.7 on 2021-09-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_name', models.CharField(max_length=120)),
                ('post_title', models.CharField(max_length=200)),
                ('post_subtitle', models.CharField(max_length=200)),
                ('post_text', models.TextField()),
            ],
        ),
    ]
