# Generated by Django 3.2.7 on 2021-09-19 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql='''
            create function core_post_trigger() returns trigger as $$
            begin
                new.vector_column :=
                    setweight(to_tsvector('pg_catalog.english', coalesce(new.post_title, '')), 'A') ||
                    setweight(to_tsvector('pg_catalog.english', coalesce(new.post_subtitle, '')), 'B') ||
                    setweight(to_tsvector('pg_catalog.english', coalesce(new.post_text, '')), 'C');
                return new; 
            end
            $$ language plpgsql;
            
            create trigger vector_column_trigger
            before insert or update on core_post
            for each row execute procedure
            core_post_trigger();
            ''',

            reverse_sql='''
                drop trigger if exists vector_column_trigger
                on core_post; 
            '''
        )
    ]
